# Generated by Django 4.2.23 on 2025-06-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregistration',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
