# Generated by Django 4.2.23 on 2025-06-15 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_eventregistration_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='approved',
        ),
        migrations.AlterField(
            model_name='eventregistration',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
